base-chart:

  extraEnv:
    INCLUDE_NAMESPACE: "prod" # single namespace 
    # EXCLUDE_NAMESPACE: "kube-system"
    # INCLUDE_LABELS: "app.kubernetes.io/name=fluent-bit"
    LOG_LEVEL: 2

  servicemonitor:
    enabled: true
    prometheus:
      namespace: monitoring
      labels:
        release: kube-prometheus-stack
        app: kube-prometheus-stack
    selector:
      matchLabels:
        app: pod-relabel
    port: http
    path: metrics
    interval: 45s

  clusterRole:
    enabled: true
    name: pod-relabel-prod-role
    rules:
      - apiGroups: [""]
        resources: ["pods", "replicasets", "deployments", "daemonsets"]
        verbs: ["get", "list", "patch", "watch"]
      - apiGroups: ["apps"]
        resources: ["replicasets", "deployments", "daemonsets"]
        verbs: ["get", "list", "patch", "watch"]

  clusterRoleBinding:
    enabled: true
    name: pod-relabel-role-prod-binding
    roleName: pod-relabel-prod-role
    serviceAccountName: pod-relabel-serviceaccount
    namespace: prod