base-chart:
  nameOverride: pod-relabel
  image:
    repository: 932213950603.dkr.ecr.us-east-1.amazonaws.com/pod-relabel
    tag: 0.0.2

  replicaCount: 1

  javaConfig:
    enabled: false

  extraEnv:


  resources:
    limits:
      #cpu: 2000m
      # memory: 4000M
    requests:
      cpu: 50m
      memory: 1800M

  service:
    serverPort: 8080
    serverPortName: http
    targetPort: http
    labels:
      version: v1
    # annotations:
    #   key: value
    type: ClusterIP

  ingress:
    enabled: false
    className: internal
    # annotations:
    #   kubernetes.io/ingress.class: internal
    paths: /
    # hosts:
    #   - app-name.dev-int.mypileus.io
