base-chart:

  extraEnv:
    # EXCLUDE_NAMESPACE: "kube-system"
    # INCLUDE_LABELS: "app.kubernetes.io/name=fluent-bit"
    LOG_LEVEL: 1

  ingress:
    enabled: true
    className: internal
    # annotations:
    #   kubernetes.io/ingress.class: internal
    paths: /
    hosts:
      - pod-relabel.dev-int.mypileus.io

  clusterRole:
    enabled: true
    name: pod-relabel-role
    rules:
      - apiGroups: [""]
        resources: ["pods", "replicasets", "deployments", "daemonsets"]
        verbs: ["get", "list", "patch", "watch"]
      - apiGroups: ["apps"]
        resources: ["replicasets", "deployments", "daemonsets"]
        verbs: ["get", "list", "patch", "watch"]

  clusterRoleBinding:
    enabled: true
    name: pod-relabel-role-binding
    roleName: pod-list-role
    serviceAccountName: pod-relabel-serviceaccount
    namespace: pod-relabel
